### ISSUE TITLE
Emissives can be seen through vehicles

### ISSUE THREAD

**Issue by Yufai** [justalemon/SimplePassive#17]
Any emissive such as lights or any markers can be seen through the vehicle. I tried `set simplepassive_alpha 255`, but it doesn't appear to have an effect.

![Screenshot (183)](https://user-images.githubusercontent.com/42881012/82487432-53d8f000-9aac-11ea-8335-9218297e8227.png)
![Screenshot (184)](https://user-images.githubusercontent.com/42881012/82487500-6c490a80-9aac-11ea-99c8-471bcd61dc79.png)
![Screenshot (185)](https://user-images.githubusercontent.com/42881012/82487502-6ce1a100-9aac-11ea-9132-a19dc739bd78.png)

**Comment by justalemon** [comment]
Does this happens with SimplePassive disabled?

**Comment by Yufai** [comment]
![Screenshot (203)](https://user-images.githubusercontent.com/42881012/82592173-81866d80-9b6e-11ea-839a-7928b4c2a3b1.png)
![Screenshot (204)](https://user-images.githubusercontent.com/42881012/82592175-82b79a80-9b6e-11ea-9857-20141d7d0ae9.png)

No it does not

**Comment by glitchdetector** [comment]
https://github.com/justalemon/SimplePassive/blob/9c8538d5a4579e4463e22228cb86d932d5535f23/SimplePassive.Client/Passive.cs#L72-L76
Rather than setting the alpha to 255, you could use `RESET_ENTITY_ALPHA`. Resetting the alpha does resolve the problem.

A convar to disable the alpha effect entirely would be appreciated aswell though.

**Comment by justalemon** [comment]
I'm going to try to use `RESET_ENTITY_ALPHA` and see what happens.

I'm also going to add a convar that completely disables the alpha changes, so the alpha of the entities will not be changed.

**Comment by justalemon** [comment]
ec710287facbab79b1a770927bd9dc6c12a65456 uses `RESET_ENTITY_ALPHA` instead of `SET_ENTITY_ALPHA` to set the visibility of the entities to the maximum.

Can you see if this fixes your problem? You can download a test build from https://ci.appveyor.com/project/justalemon/simplepassive/builds/33188713/artifacts.

**Comment by justalemon** [comment]
The 6 lights on the center would be visible thru entities.

![emmissive](https://user-images.githubusercontent.com/11861253/83224865-745c1680-a14c-11ea-9107-2aab244e12ae.PNG)

That is no longer the case:

![tow](https://user-images.githubusercontent.com/11861253/83224927-9b1a4d00-a14c-11ea-9583-03540e5625dd.PNG)

(Sorry about the low quality pics, my PC is trash)
